FIRST_NAME = 'first_name'
LAST_NAME = 'last_name'
EMAIL_ID = 'email_id'
CARD_TYPE = 'card_type'
AMOUNT = 'amount'
STATUS_ID = 'status_id'
UUID = 'uuid'
PASSWORD = 'password'
STATUS = 'status'
DATA = 'data'
SUCCESS = 'success'
ERROR = 'error'
IS_FIRST_TIME_LOGIN ='is_first_time_login'
IS_STUDENT = 'is_student'
IS_SUPPLIER = 'is_supplier'
IS_ADMIN = 'is_admin'
MODIFIED_AT = 'modified_date_time'
MODIFIED_BY = 'modified_by'
CREATED_AT='created_date_time'
CREATED_BY='created_by'
POST_METHOD = 'POST'
COURSE_IMAGE = 'course_image'
COURSE_NAME = 'course_name'
COURSE_LEVEL_ID = 'course_level_id'
COURSE_LENGTH = 'course_length'
COURSE_CATEGORY_ID = 'course_category_id'
COURSE_CATEGORY_NAME = 'course_category_category_name'
COURSE_TYPE_ID = 'course_type_id'
FEE_TYPE_NAME = 'fee_type_name'
FEE_TYPE_ID = 'fee_type_id'
COURSE_PRICE='course_price'
LEVEL_NAME = 'level_name'
ADDITIONAL_INFORMATION='additional_information'
TYPE_NAME = 'type_name'
ID = 'id'
SUBCATEGORY_NAME_ID='subcategory_name_id'
CATEGORY_NAME_ID = 'category_name_id'
COURSE_SUBCATEGORY_ID = 'course_subcategory_id'
SUBCATEGORY_NAME='subcategory_name'
SUBCATEGORY_IMAGE = 'subcategory_image'
CATEGORY_NAME = 'category_name'
TRUE = 'true'
FALSE = 'false'
OTP_EMAIL_HTML = 'email-password.html'
USER_WELCOME_HTML = 'user-welcome.html'

RESETPASSWORD_HTML = 'email-link.html'
USER_TYPE_ID = 'user_type_id'
ORGANIZATION_LOCATION = 'organization_location'
SUB_AREA = 'sub_area'
SUPPLIER_ID = 'supplier_id'
SUPPLIER_S = 'Supplier'
ADMIN_S = 'Admin'

FULLNAME = 'fullname'
USER_TYPE='user_type'
BLOG_CATEGORY_ID='blog_category_id'
PHONE_NUMBER = 'phone_number'
COURSE_CHECKOUT_LINK = 'course_checkout_link'
COURSE_FOR_ORGANIZATION='course_for_organization'
COURSE_LANGUAGE='course_language'
MESSAGE = 'message'
ORGANIZATION_DOMAIN = 'organization_domain'
EVENT_IMAGE = "event_image"
EVENT_PUBLISH_ON = "event_publish_on"
EVENT_NAME = "event_name"
EVENT_CHOOSE_TYPE = "event_choose_type"
EVENT_CATEGORY = "event_category"
BANNER_VIDEO_LINK = "banner_video_link"
START_DATE = "start_date"
START_TIME = "start_time"
FEES_TYPE = "fees_type"
EVENT_TYPE = "event_type"
EVENT_PRICE = "event_price"
CHECKOUT_LINK = "checkout_link"
EVENT_SMALL_DESCRIPTION = "event_small_description"
EVENT_DESCRIPTION = "event_description"
EVENT_LOCATION = "event_location"
EVENT_ORGANIZER = "event_organizer" 
EVENT_SUBSCRIBER = "event_subscriber"
IS_FEATURED = "is_featured"
VIDEO_TITLE = 'video_title'
VIDEO_FILES = 'video_files'
VIDEO_FILES_ID = 'video_files_id'
FILE_TITLE = 'file_title'
DOCUMENT_FILES  = 'document_files'
DOCUMENT_FILES_ID = 'document_files_id'

