USERSIGNUP_TABLE = 'UserSignup'
COURSEDETAILS_TABLE='CourseDetails'
COURSE_SUBCATEGORY_TABLE = 'CourseSubCategoryDetails'
COURSE_CATEGORY_TABLE = 'CourseCategoryDetails'
COURSE_TYPE_TABLE='CourseType'
FEE_TYPE_TABLE='FeeType'
COURSE_LEVEL_TABLE='CourseLevel'
BLOGDETAILS_TABLE='BlogDetails'
CONTACT_FORM_TABLE='ContactFormLead'
USER_TYPE_TABLE = 'UserType'
USER_PROFILE_TABLE='UserProfile'


# CMS
HOMEPAGECMS_TABLE = 'HomePageCMS'
ABOUTUSCMS_TABLE='AboutUsPageCMS'
CONTACTUSCMS_TABLE = 'ContactUsPageCMS'

PRIVACY_POLICY_CMS_TABLE = 'PrivacyPolicyCMS'
TERMS_CONDITION_CMS_TABLE = 'TermsConditionCMS'