from eddi_app.constants.constants import DEVICE_TOKEN


USERSIGNUP_TABLE = 'UserSignup'
COURSEDETAILS_TABLE='CourseDetails'
COURSE_SUBCATEGORY_TABLE = 'CourseSubCategoryDetails'
COURSE_CATEGORY_TABLE = 'CourseCategoryDetails'
COURSE_TYPE_TABLE='CourseType'
FEE_TYPE_TABLE='FeeType'
COURSE_LEVEL_TABLE='CourseLevel'
BLOGDETAILS_TABLE='BlogDetails'
CONTACT_FORM_TABLE='ContactFormLead'
USER_TYPE_TABLE = 'UserType'
USER_PROFILE_TABLE='UserProfile'
COURSE_ENROLL_TABLE='CourseEnroll'
USER_PAYMENT_DETAIL ='UserPaymentDetail' # Add table
FAVOURITE_COURSE_TABLE = "FavouriteCourse"
TOKEN_TABLE = 'NonBuiltInUserToken'
EVENT_AD_TABLE = "EventAd"
DEVICE_TOKEN_TABLE = 'UserDeviceToken'


# CMS
HOMEPAGECMS_TABLE = 'HomePageCMS'
ABOUTUSCMS_TABLE='AboutUsPageCMS'
CONTACTUSCMS_TABLE = 'ContactUsPageCMS'
HEADER_FOOTERCMS_TABLE = 'Header_FooterCMS'

PRIVACY_POLICY_CMS_TABLE = 'PrivacyPolicyCMS'
TERMS_CONDITION_CMS_TABLE = 'TermsConditionCMS'

PRIVACY_POLICY_CMS_SUPPLIER_TABLE = 'PrivacyPolicyCMSSupplier'
TERMS_CONDITION_CMS_SUPPLIER_TABLE = 'TermsConditionCMSSupplier'



EVENTAD_PAYMENT_DETAIL_TABLE = 'EventAdPaymentDetail'
EVENTAD_ENROLL_TABLE = 'EventAdEnroll'

RECRUITMENTAD_TABLE = 'RecruitmentAd'

SUPPLIER_ORGANIZATION_PROFILE_TABLE = 'SupplierOrganizationProfile'
SUPPLIER_PROFILE_TABLE = 'SupplierProfile'