version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/eddi-backend
    runas: ubuntu
hooks:
  AfterInstall:
    - location: afterInstall.sh
      timeout: 100    
  ApplicationStart:
    - location: applicationStart.sh
      timeout: 100
