# Generated by Django 3.1.7 on 2022-03-07 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category Name')),
                ('category_image', models.FileField(upload_to='category_image/', verbose_name='Category Image')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
            ],
            options={
                'verbose_name': 'Course Category Table',
            },
        ),
        migrations.CreateModel(
            name='utl_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('is_student', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_first_time_login', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'User Signup Table',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('fee_type_name', models.CharField(max_length=150, verbose_name='Fee Type Name')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Fee Type Table',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('type_name', models.CharField(max_length=150, verbose_name='Course Type Name')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Course Type Table',
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('level_name', models.CharField(max_length=150, verbose_name='Course Level Name')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Course Level Table',
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('course_image', models.FileField(upload_to='course_image/', verbose_name='Course Image')),
                ('course_name', models.CharField(max_length=150, verbose_name='Course Name')),
                ('course_length', models.IntegerField(default=0, verbose_name='Course Length')),
                ('course_price', models.IntegerField(default=0, verbose_name='Course Price')),
                ('additional_information', models.TextField(max_length=1500, verbose_name='Additional Information')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursecategorydetails', verbose_name='Course Category')),
                ('course_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.courselevel', verbose_name='Course Level')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursetype', verbose_name='Course Type')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.feetype', verbose_name='Fee Type')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Course Details Table',
            },
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status'),
        ),
    ]
