# Generated by Django 3.1.7 on 2022-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0002_auto_20220307_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
