# Generated by Django 3.1.7 on 2022-03-09 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0003_auto_20220307_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubCategoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID')),
                ('subcategory_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Category Name')),
                ('subcategory_image', models.FileField(blank=True, null=True, upload_to='category_image/', verbose_name='Category Image')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursecategorydetails', verbose_name='Category Name')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Course Sub Category Table',
            },
        ),
    ]
