# Generated by Django 3.1.7 on 2022-03-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0004_coursesubcategorydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='course_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursesubcategorydetails', verbose_name='Course Category'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='organization_location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='sub_area',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='course_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Course Price'),
        ),
    ]
