# Generated by Django 3.1.7 on 2022-03-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0005_auto_20220309_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='organization_location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Organization Location'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='sub_area',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub Area'),
        ),
        migrations.CreateModel(
            name='approval_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=60)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status')),
            ],
            options={
                'verbose_name': 'Approval Status Table',
            },
        ),
    ]
