# Generated by Django 3.1.7 on 2022-03-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0006_auto_20220309_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval_status',
            name='status',
        ),
        migrations.AddField(
            model_name='approval_status',
            name='status',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.utl_status'),
        ),
    ]
