# Generated by Django 3.1.7 on 2022-03-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0007_auto_20220309_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='is_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status'),
        ),
        migrations.AddField(
            model_name='coursesubcategorydetails',
            name='is_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
