# Generated by Django 3.1.7 on 2022-03-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0008_auto_20220310_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
