# Generated by Django 3.1.7 on 2022-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0009_auto_20220310_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=60, verbose_name='User Type')),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Type Table',
            },
        ),
    ]
