# Generated by Django 3.1.7 on 2022-03-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0010_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='is_supplier',
        ),
        migrations.AddField(
            model_name='usersignup',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usertype', verbose_name='User Type'),
        ),
    ]
