# Generated by Django 3.1.7 on 2022-03-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0011_auto_20220310_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubcategorydetails',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type_id': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'user_type_id': 1}, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup'),
        ),
    ]
