# Generated by Django 3.1.7 on 2022-03-15 19:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0012_auto_20220311_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_1_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_1_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('section_1_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('section_1_button_link', models.URLField(blank=True, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='HomePageCMSBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=50, null=True)),
                ('banner', models.ImageField(upload_to='homepage_banner/', verbose_name='Banner Image')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
        ),
    ]
