# Generated by Django 3.1.7 on 2022-03-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0013_homepagecms_homepagecmsbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecms',
            name='section_1_image',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.HomePageCMSBanner', verbose_name='Banner Image'),
        ),
    ]
