# Generated by Django 3.1.7 on 2022-03-15 20:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0014_homepagecms_section_1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecms',
            name='section_2_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_2_heading',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_2_left_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Left Button URL'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_2_left_button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Left Button Text'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_2_right_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Right Button URL'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_2_right_button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Right Button Text'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_3_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_3_button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_3_heading',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_4_heading',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_5_heading',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_6_description',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_6_heading',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_8_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_8_button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_8_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_8_heading',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_8_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='TestinomialsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', ckeditor.fields.RichTextField(blank=True, verbose_name='User Review')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup', verbose_name='User Details')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageCMSPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_logo', models.ImageField(upload_to='homepage_partner_logo/', verbose_name='Partner Logo')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='blog_image/', verbose_name='Blog Image')),
                ('blog_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Blog Title')),
                ('blog_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Blog Description')),
                ('written_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Written by')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_4_logo',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.HomePageCMSPartners', verbose_name='Partner Logo'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_5_blog',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.BlogDetails', verbose_name='Blog'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_6_testinomials',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.TestinomialsDetails', verbose_name='Testinomials'),
        ),
    ]
