# Generated by Django 3.1.7 on 2022-03-15 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0015_auto_20220315_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecms',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='modified_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Modified Date Time'),
            preserve_default=False,
        ),
    ]
