# Generated by Django 3.1.7 on 2022-03-15 21:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0016_auto_20220315_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPageCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_1_image', models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='Banner Image')),
                ('section_1_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_1_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('section_1_button_link', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('section_2_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_2_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('section_2_video', models.FileField(blank=True, null=True, upload_to='about_us/', verbose_name='Video Upload')),
                ('section_3_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_3_image', models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='Image')),
                ('section_3_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('section_3_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('section_3_button_link', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('section_4_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_4_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('section_4_button_link', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('section_4_courses', models.ManyToManyField(blank=True, null=True, to='eddi_app.CourseDetails', verbose_name='Newest Courses')),
            ],
            options={
                'verbose_name': 'About Us Page',
            },
        ),
    ]
