# Generated by Django 3.1.7 on 2022-03-17 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0018_auto_20220316_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='coursesubcategorydetails',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursecategorydetails', verbose_name='Sub Category Name'),
        ),
    ]
