# Generated by Django 3.1.7 on 2022-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0019_auto_20220317_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPageCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_1_image', models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='Banner Image')),
                ('section_1_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_1_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('section_1_button_link', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('section_2_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_2_address', models.CharField(blank=True, max_length=80, null=True, verbose_name='Address')),
                ('section_2_contact', models.CharField(blank=True, max_length=80, null=True, verbose_name='Contact Number')),
                ('section_2_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID')),
                ('section_2_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('section_2_button_link', models.URLField(blank=True, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Contact Us Page',
            },
        ),
    ]
