# Generated by Django 3.1.7 on 2022-03-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0020_contactuspagecms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuspagecms',
            name='section_2_button_link',
        ),
    ]
