# Generated by Django 3.1.7 on 2022-03-17 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0022_contactformlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformlead',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='contactformlead',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactformlead',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='contactformlead',
            name='modified_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Modified Date Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactformlead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status'),
        ),
    ]
