# Generated by Django 3.1.7 on 2022-03-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0025_usersignup_first_name_usersignup_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='blog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursecategorydetails', verbose_name='Blog Category'),
        ),
    ]
