# Generated by Django 3.1.7 on 2022-03-22 04:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0026_blogdetails_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdetails',
            options={'verbose_name': 'Blog Table'},
        ),
        migrations.CreateModel(
            name='TermsConditionCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_1_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_1_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('section_1_button_link', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('section_2_main_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Main Heading')),
                ('section_2_left_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Left Heading')),
                ('section_2_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('section_1_image', models.ManyToManyField(blank=True, null=True, to='eddi_app.HomePageCMSBanner', verbose_name='Banner Image')),
            ],
            options={
                'verbose_name': 'Terms & Condition Page',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_1_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading')),
                ('section_1_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('section_1_button_link', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('section_2_main_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Main Heading')),
                ('section_2_left_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Left Heading')),
                ('section_2_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('section_2_sub_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Sub Heading')),
                ('section_2_sub_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Sub Description')),
                ('section_2_last_heading', models.CharField(blank=True, max_length=80, null=True, verbose_name='Last Heading')),
                ('section_2_last_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Last Description')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('section_1_image', models.ManyToManyField(blank=True, null=True, to='eddi_app.HomePageCMSBanner', verbose_name='Banner Image')),
            ],
            options={
                'verbose_name': 'Privacy Policy Page',
            },
        ),
    ]
