# Generated by Django 3.1.7 on 2022-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0028_auto_20220322_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformlead',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
