# Generated by Django 3.1.7 on 2022-03-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0029_auto_20220323_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformlead',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
