# Generated by Django 3.1.7 on 2022-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0031_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Id'),
        ),
    ]
