# Generated by Django 3.1.7 on 2022-03-25 20:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0032_auto_20220325_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategorydetails',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
