# Generated by Django 3.1.7 on 2022-03-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0033_coursecategorydetails_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategorydetails',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Color'),
        ),
    ]
