# Generated by Django 3.1.7 on 2022-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0034_auto_20220325_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='course_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
