# Generated by Django 3.1.7 on 2022-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0036_remove_coursedetails_course_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email Id'),
        ),
    ]
