# Generated by Django 3.1.7 on 2022-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0037_auto_20220326_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval_status',
            name='status',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.utl_status', verbose_name='Status'),
        ),
    ]
