# Generated by Django 3.1.7 on 2022-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0038_auto_20220326_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='course_for_organization',
            field=models.BooleanField(default=False),
        ),
    ]
