# Generated by Django 3.1.7 on 2022-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0039_coursedetails_course_for_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='course_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
