# Generated by Django 3.1.7 on 2022-03-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0040_coursedetails_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status'),
        ),
    ]
