# Generated by Django 3.1.7 on 2022-03-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0042_coursedetails_course_checkout_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='organization_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
