# Generated by Django 3.1.7 on 2022-03-28 07:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0043_coursedetails_organization_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecms',
            name='section_1_description_sv',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagecms',
            name='section_1_heading_sv',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Heading Swedish'),
        ),
    ]
