# Generated by Django 3.1.7 on 2022-03-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0044_auto_20220328_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecms',
            name='section_1_description_sv',
        ),
        migrations.RemoveField(
            model_name='homepagecms',
            name='section_1_heading_sv',
        ),
    ]
