# Generated by Django 3.1.7 on 2022-03-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0045_auto_20220328_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type_id': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup'),
        ),
    ]
