# Generated by Django 3.1.7 on 2022-03-29 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eddi_app', '0048_auto_20220329_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonbuiltinusertoken',
            name='email_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='eddi_app.usersignup', verbose_name='email_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nonbuiltinusertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
