# Generated by Django 3.1.7 on 2022-03-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0050_auto_20220329_0608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonBuiltInUserToken',
        ),
    ]
