# Generated by Django 3.1.7 on 2022-03-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0053_auto_20220329_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonbuiltinusertoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='eddi_app.usersignup', verbose_name='email_id'),
        ),
    ]
