# Generated by Django 3.1.7 on 2022-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0054_auto_20220329_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
