# Generated by Django 4.0 on 2022-03-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0056_userpaymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Name')),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID')),
                ('is_favourite', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Favourite Course Created Date Time')),
            ],
        ),
    ]
