# Generated by Django 4.0 on 2022-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0058_userpaymentdetail_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenroll',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='supplier email'),
        ),
    ]
