# Generated by Django 4.0 on 2022-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0059_courseenroll_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenroll',
            name='course_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Category'),
        ),
    ]
