# Generated by Django 4.0 on 2022-04-06 11:37

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0060_courseenroll_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event_image', models.FileField(blank=True, null=True, upload_to='event_image/', verbose_name='Event Image')),
                ('event_publish_on', models.DateTimeField(auto_now_add=True, verbose_name='Event Publish On')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Name')),
                ('event_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Category')),
                ('banner_video_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Banner Link')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Event Start Date')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='Event Start Time')),
                ('fees_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fees Type')),
                ('event_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Type')),
                ('event_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Event Price')),
                ('checkout_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Checkout Link')),
                ('event_small_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Event Small Description')),
                ('event_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Event Description')),
                ('event_location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Location')),
                ('event_organizer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organizer')),
                ('event_subscriber', models.IntegerField(blank=True, default=0, null=True, verbose_name='Course Subscriber')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Favourite Course Created Date Time')),
            ],
        ),
    ]
