# Generated by Django 4.0 on 2022-04-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0061_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventAd',
        ),
    ]
