# Generated by Django 4.0 on 2022-04-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0063_alter_eventad_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventad',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
        migrations.AlterField(
            model_name='eventad',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Event Start Time'),
        ),
    ]
