# Generated by Django 4.0 on 2022-04-07 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0064_alter_eventad_start_date_alter_eventad_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventad',
            name='event_publish_on',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Publish on'),
        ),
        migrations.AlterField(
            model_name='eventad',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Video Title')),
                ('video_files', models.FileField(blank=True, null=True, upload_to='course_video/', verbose_name='Video Files')),
                ('file_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='File Title')),
                ('document_files', models.FileField(blank=True, null=True, upload_to='document_files/', verbose_name='Document Files')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Favourite Course Created Date Time')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursedetails', verbose_name='Course')),
            ],
        ),
    ]
