# Generated by Django 4.0 on 2022-04-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0065_alter_eventad_event_publish_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventad',
            options={'verbose_name': 'EventAd Table'},
        ),
        migrations.AddField(
            model_name='eventad',
            name='event_choose_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Choose Type'),
        ),
        migrations.AlterField(
            model_name='eventad',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='EventAd Created Date Time'),
        ),
    ]
