# Generated by Django 4.0 on 2022-04-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0066_alter_eventad_options_eventad_event_choose_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventad',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status'),
        ),
    ]
