# Generated by Django 4.0 on 2022-04-07 12:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0067_eventad_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_FooterCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eddi_logo_header', models.ImageField(blank=True, null=True, upload_to='eddi_logo/', verbose_name='Eddi Logo Header')),
                ('button_1_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button 1 Text')),
                ('button_2_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button 2 Text')),
                ('button_3_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button 3 Text')),
                ('button_4_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button 4 Text')),
                ('login_button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Login Button Text')),
                ('eddi_logo_footer', models.ImageField(blank=True, null=True, upload_to='eddi_logo/', verbose_name='Eddi Logo Footer')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Footer Description')),
                ('follow_us_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Follow Us Text')),
                ('social_media_icon1', models.ImageField(blank=True, null=True, upload_to='social_media_icon/', verbose_name='Social Media Icon 1')),
                ('social_media_icon2', models.ImageField(blank=True, null=True, upload_to='social_media_icon/', verbose_name='Social Media Icon 2')),
                ('social_media_icon3', models.ImageField(blank=True, null=True, upload_to='social_media_icon/', verbose_name='Social Media Icon 3')),
                ('copyright_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Copyright Text')),
                ('quick_link_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quicklink Text')),
                ('quick_link_button_text1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quicklink Button Text1')),
                ('quick_link_button_text2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quicklink Button Text2')),
                ('quick_link_button_text3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quicklink Button Text3')),
                ('quick_link_button_text4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quicklink Button Text4')),
                ('quick_link_button_text5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quicklink Button Text5')),
                ('quick_link_button_text6', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quicklink Button Text6')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
            ],
            options={
                'verbose_name': 'Header_FooterCMS',
            },
        ),
    ]
