# Generated by Django 3.2.11 on 2022-04-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0068_header_footercms'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDocumentMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='course_material_doc/', verbose_name='Document Files')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVideoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_material_video/', verbose_name='Video Files')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='document_files',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='video_files',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='document_files',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.MaterialDocumentMaterial', verbose_name='Document Files'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='video_files',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.MaterialVideoMaterial', verbose_name='Video Files'),
        ),
    ]
