# Generated by Django 4.0 on 2022-04-09 15:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0069_auto_20220408_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitmentAd_File', models.FileField(blank=True, null=True, upload_to='recruitment_file/', verbose_name='Recruitment File')),
                ('recruitmentAd_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='RecruitmentAd Title')),
                ('recruitmentAd_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='RecruitmentAd Description')),
                ('recruitmentAd_banner_video_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='RecruitmentAd Banner Link')),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID')),
                ('recruitmentAd_Expiry', models.DateField(blank=True, null=True, verbose_name='RecruitmentAd Expiry Date')),
                ('subscriber_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Subscriber Count')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('approval', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status', verbose_name='Approval Status')),
                ('status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
        ),
    ]
