# Generated by Django 4.0 on 2022-04-09 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0070_recruitmentad'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentad',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
