# Generated by Django 4.0 on 2022-04-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0071_recruitmentad_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Name')),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID')),
                ('card_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card Type')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Payment Created Date Time')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Status')),
            ],
        ),
        migrations.CreateModel(
            name='EventAdEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event name')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Admin Email')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('payment_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.eventadpaymentdetail', verbose_name='Payment Detail')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.userprofile', verbose_name='User Profile')),
            ],
        ),
    ]
