# Generated by Django 4.0 on 2022-04-12 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0072_eventadpaymentdetail_eventadenroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadenroll',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='eventadpaymentdetail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
