# Generated by Django 4.0 on 2022-04-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0073_eventadenroll_uuid_eventadpaymentdetail_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadpaymentdetail',
            name='uuid',
        ),
    ]
