# Generated by Django 4.0 on 2022-04-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0073_eventadpaymentdetail_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadpaymentdetail',
            name='uuid',
        ),
        migrations.AddField(
            model_name='eventad',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meeting Link'),
        ),
        migrations.AddField(
            model_name='eventad',
            name='meeting_passcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Passcode'),
        ),
    ]
