# Generated by Django 4.0 on 2022-04-12 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0074_remove_eventadpaymentdetail_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadpaymentdetail',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='eventadenroll',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
