# Generated by Django 4.0 on 2022-04-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0075_alter_eventad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval_status',
            name='status',
        ),
    ]
