# Generated by Django 4.0 on 2022-04-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0075_eventadpaymentdetail_uuid_alter_eventadenroll_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadenroll',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='eventadpaymentdetail',
            name='uuid',
        ),
    ]
