# Generated by Django 4.0 on 2022-04-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0076_remove_approval_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='course_starting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Course Start Date'),
        ),
    ]
