# Generated by Django 4.0 on 2022-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0078_privacypolicycmssupplier_termsconditioncmssupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meeting Link'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='meeting_passcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Passcode'),
        ),
    ]
