# Generated by Django 3.2.6 on 2022-04-20 11:02

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0079_coursedetails_meeting_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Organizational Name')),
                ('organization_email', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Oraganization Email')),
                ('organization_website', models.CharField(blank=sqlalchemy.sql.expression.true, max_length=250, null=True, verbose_name='organization Website')),
                ('organization_address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Organization Address')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('brif_information', models.TextField(blank=True, max_length=250, null=True, verbose_name='Brif Information on Organization')),
                ('organization_phone_number', models.BigIntegerField(blank=True, null=True, verbose_name='Organization Phone Number')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person at Eddi')),
                ('course_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Category')),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Category')),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='organization_logo/', verbose_name='Organization Logo')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Name')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('phone_number', models.BigIntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('supplier_image', models.ImageField(blank=True, null=True, upload_to='supplier_image/', verbose_name='Supplier Image')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
            ],
        ),
    ]
