# Generated by Django 3.2.6 on 2022-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0080_supplierorganizationprofile_supplierprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Supplier Email'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Supplier Email'),
        ),
        migrations.AlterField(
            model_name='supplierorganizationprofile',
            name='organization_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Oraganization Email'),
        ),
    ]
