# Generated by Django 4.0 on 2022-04-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0080_coursematerial_uuid_materialdocumentmaterial_uuid_and_more'),
        ('eddi_app', '0081_auto_20220420_1259'),
    ]

    operations = [
    ]
