# Generated by Django 4.0 on 2022-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0082_merge_20220421_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoice/', verbose_name='Invoice File')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Name')),
            ],
        ),
        migrations.AlterField(
            model_name='supplierorganizationprofile',
            name='organization_website',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='organization Website'),
        ),
    ]
