# Generated by Django 4.0 on 2022-04-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0083_invoicedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceVATCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_value', models.IntegerField(blank=True, null=True, verbose_name='VAT Value Percentage')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
            ],
        ),
    ]
