# Generated by Django 4.0 on 2022-04-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0084_invoicevatcms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_interests',
            field=models.JSONField(blank=True, null=True, verbose_name='User Interests'),
        ),
    ]
