# Generated by Django 4.0 on 2022-04-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0085_userprofile_location_userprofile_user_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDataEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoice/', verbose_name='Invoice File')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Name')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='usersignup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='is_login_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Is Login From'),
        ),
    ]
