# Generated by Django 4.0 on 2022-04-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0086_invoicedataevent_usersignup_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitmentad',
            old_name='approval',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='recruitmentad',
            name='supplier_email',
        ),
        migrations.AddField(
            model_name='recruitmentad',
            name='supplier_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.supplierprofile', verbose_name='Supplier Profile'),
        ),
        migrations.AddField(
            model_name='recruitmentad',
            name='user_profile',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.UserProfile', verbose_name='User Profile'),
        ),
    ]
