# Generated by Django 4.0 on 2022-04-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0087_rename_approval_recruitmentad_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='var_charges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.invoicevatcms', verbose_name='Invoice Vat'),
        ),
    ]
