# Generated by Django 4.0 on 2022-05-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0089_blogdetails_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdocumentmaterial',
            name='file_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='materialvideomaterial',
            name='actual_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Actual Video Duration'),
        ),
    ]
