# Generated by Django 4.0 on 2022-05-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0090_materialdocumentmaterial_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook Profile'),
        ),
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='linkedIn_profile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IFSC Code'),
        ),
    ]
