# Generated by Django 4.0 on 2022-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0091_supplierorganizationprofile_facebook_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadenroll',
            name='admin_email',
        ),
        migrations.AddField(
            model_name='eventadenroll',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='User Email'),
        ),
    ]
