# Generated by Django 4.0 on 2022-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0092_remove_eventadenroll_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspagecms',
            name='section_2_latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contactuspagecms',
            name='section_2_longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude'),
        ),
    ]
