# Generated by Django 4.0 on 2022-05-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0095_remove_invoicedata_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorganizationprofile',
            name='organization_phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Organization Phone Number'),
        ),
    ]
