# Generated by Django 4.0 on 2022-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0096_alter_supplierorganizationprofile_organization_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('video_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Video')),
                ('document_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document')),
                ('is_complete', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration')),
            ],
        ),
    ]
