# Generated by Django 4.0 on 2022-05-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0098_courserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.userprofile'),
        ),
    ]
