# Generated by Django 4.0 on 2022-05-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0100_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='supplier_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.supplierorganizationprofile'),
        ),
    ]
