# Generated by Django 4.0 on 2022-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0102_coursedetails_target_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='receiver'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sender'),
        ),
    ]
