# Generated by Django 4.0 on 2022-05-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0103_notification_receiver_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usersignup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup'),
        ),
    ]
