# Generated by Django 4.0.3 on 2022-05-15 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0104_userprofile_usersignup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformlead',
            options={'verbose_name': 'Contact Form Lead Table'},
        ),
        migrations.AlterModelOptions(
            name='courseenroll',
            options={'verbose_name': 'Course Enroll'},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name': 'Course Material'},
        ),
        migrations.AlterModelOptions(
            name='coursematerialstatus',
            options={'verbose_name': 'Course Material Status'},
        ),
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name': 'Course Rating Table'},
        ),
        migrations.AlterModelOptions(
            name='eventadenroll',
            options={'verbose_name': 'Event Ad Enroll'},
        ),
        migrations.AlterModelOptions(
            name='eventadpaymentdetail',
            options={'verbose_name': 'Event Ad Payment Detail'},
        ),
        migrations.AlterModelOptions(
            name='favouritecourse',
            options={'verbose_name': 'Favourite Course'},
        ),
        migrations.AlterModelOptions(
            name='homepagecmsbanner',
            options={'verbose_name': 'Home Page CMS Banner Table'},
        ),
        migrations.AlterModelOptions(
            name='homepagecmspartners',
            options={'verbose_name': 'Home Page CMS Partners Table'},
        ),
        migrations.AlterModelOptions(
            name='invoicedata',
            options={'verbose_name': 'Invoice Data'},
        ),
        migrations.AlterModelOptions(
            name='invoicedataevent',
            options={'verbose_name': 'Invoice Data Event'},
        ),
        migrations.AlterModelOptions(
            name='invoicevatcms',
            options={'verbose_name': 'Invoice VAT Table'},
        ),
        migrations.AlterModelOptions(
            name='materialdocumentmaterial',
            options={'verbose_name': 'Material Document Material'},
        ),
        migrations.AlterModelOptions(
            name='materialvideomaterial',
            options={'verbose_name': 'Material Video Material'},
        ),
        migrations.AlterModelOptions(
            name='nonbuiltinusertoken',
            options={'verbose_name': 'Non BuiltIn User Token'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification Table'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentad',
            options={'verbose_name': 'Recruitment Ad'},
        ),
        migrations.AlterModelOptions(
            name='supplierorganizationprofile',
            options={'verbose_name': 'Supplier Organization Profile Table'},
        ),
        migrations.AlterModelOptions(
            name='supplierprofile',
            options={'verbose_name': 'Supplier Profile'},
        ),
        migrations.AlterModelOptions(
            name='testinomialsdetails',
            options={'verbose_name': 'Testinomials Details Table'},
        ),
        migrations.AlterModelOptions(
            name='userpaymentdetail',
            options={'verbose_name': 'User Payment Detail'},
        ),
        migrations.AlterModelOptions(
            name='usersignup',
            options={'verbose_name': 'User Signup Table'},
        ),
        migrations.AlterField(
            model_name='approval_status',
            name='value',
            field=models.CharField(blank=True, max_length=60, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='coursecategorydetails',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='course_for_organization',
            field=models.BooleanField(default=False, verbose_name='Course For Organization'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='course_language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Language'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='is_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status', verbose_name='is_approved'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='organization_domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Domain'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='supplier_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.supplierorganizationprofile', verbose_name='Supplier Organization'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date_time'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='coursematerialstatus',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is_complete'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursedetails', verbose_name='course_name'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.userprofile', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='coursesubcategorydetails',
            name='is_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status', verbose_name='is_approved'),
        ),
        migrations.AlterField(
            model_name='coursesubcategorydetails',
            name='subcategory_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sub Category Name'),
        ),
        migrations.AlterField(
            model_name='coursesubcategorydetails',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type_id': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='eventad',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='eventad',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is_featured'),
        ),
        migrations.AlterField(
            model_name='eventad',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='favouritecourse',
            name='is_favourite',
            field=models.BooleanField(default=False, verbose_name='is_favourite'),
        ),
        migrations.AlterField(
            model_name='homepagecmsbanner',
            name='image_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Image Title'),
        ),
        migrations.AlterField(
            model_name='homepagecmspartners',
            name='image_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Image Title'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date_time'),
        ),
        migrations.AlterField(
            model_name='invoicedataevent',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date_time'),
        ),
        migrations.AlterField(
            model_name='materialdocumentmaterial',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date_time'),
        ),
        migrations.AlterField(
            model_name='materialdocumentmaterial',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='materialvideomaterial',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date_time'),
        ),
        migrations.AlterField(
            model_name='materialvideomaterial',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date_time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_clear',
            field=models.BooleanField(default=False, verbose_name='is_clear'),
        ),
        migrations.AlterField(
            model_name='recruitmentad',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date_time'),
        ),
        migrations.AlterField(
            model_name='recruitmentad',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='recruitmentad',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='supplierorganizationprofile',
            name='brif_information',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Brief Information on Organization'),
        ),
        migrations.AlterField(
            model_name='supplierorganizationprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='testinomialsdetails',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agree_ads_terms',
            field=models.BooleanField(default=True, verbose_name='agree ads terms'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usersignup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup', verbose_name='User Signup'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='is_authenticated'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_first_time_login',
            field=models.BooleanField(default=True, verbose_name='is First Time Login'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='utl_status',
            name='value',
            field=models.CharField(blank=True, max_length=60, verbose_name='Value'),
        ),
    ]
