# Generated by Django 4.0 on 2022-05-17 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0105_alter_contactformlead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialvideomaterial',
            options={},
        ),
        migrations.AddField(
            model_name='coursematerialstatus',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_date_time'),
            preserve_default=False,
        ),
    ]
