# Generated by Django 4.0 on 2022-05-18 09:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0106_alter_coursematerial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourseCategoryCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Image Title')),
            ],
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='category_overview',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Category Overview'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='enrollment_process',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Enrollment_Process'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='enrollment_process_description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Enrollment_Process_Description'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='key_highlights',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Key_highlights'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='key_highlights_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Key_highlights_Description'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='step_1_description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Step_1_Description'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='step_1_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Step_1_text'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='step_2_description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Step_2_Description'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='step_2_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Step_2_text'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='step_3_description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Step_3_Description'),
        ),
        migrations.AddField(
            model_name='coursecategorydetails',
            name='step_3_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Step_3_text'),
        ),
    ]
