# Generated by Django 4.0 on 2022-05-18 09:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0107_maincoursecategorycms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsonEddiCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name="Whats'on Eddi")),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
            ],
            options={
                'verbose_name': "Whats'on Eddi CMS",
            },
        ),
        migrations.DeleteModel(
            name='MainCourseCategoryCMS',
        ),
    ]
