# Generated by Django 4.0 on 2022-05-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0109_usersignup_is_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='is_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status', verbose_name='is_approved'),
        ),
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status'),
        ),
    ]
