# Generated by Django 4.0 on 2022-05-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0110_supplierorganizationprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Reject_Rason'),
        ),
    ]
