# Generated by Django 4.0 on 2022-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0111_supplierorganizationprofile_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinomialsdetails',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='testinomialsdetails',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UserName'),
        ),
    ]
