# Generated by Django 4.0 on 2022-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0112_testinomialsdetails_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventad',
            name='event_for_organization',
            field=models.BooleanField(default=False, verbose_name='Event For Organization'),
        ),
        migrations.AddField(
            model_name='eventad',
            name='organization_domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Domain'),
        ),
    ]
