# Generated by Django 4.0 on 2022-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0113_eventad_event_for_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='course_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Course Expiry Date'),
        ),
    ]
