# Generated by Django 4.0.3 on 2022-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0114_coursedetails_course_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name': 'Course Material'},
        ),
        migrations.AlterModelOptions(
            name='materialvideomaterial',
            options={'verbose_name': 'Material Video Material'},
        ),
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='rejection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rejection'),
        ),
    ]
