# Generated by Django 4.0.3 on 2022-05-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0116_remove_supplierorganizationprofile_rejection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='sender'),
        ),
    ]
