# Generated by Django 4.0.3 on 2022-05-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0118_contactuspagecms_sv_header_footercms_sv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='approved_once',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
    ]
