# Generated by Django 4.0.3 on 2022-05-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0119_supplierorganizationprofile_approved_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='is_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status', verbose_name='is_approved'),
        ),
    ]
