# Generated by Django 4.0.3 on 2022-05-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0121_alter_homepagecms_sv_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformlead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactformlead_sv',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userpersonalprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
    ]
