# Generated by Django 4.0.3 on 2022-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0123_userprofilecms_userprofilecms_sv'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_sv',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Address'),
        ),
    ]
