# Generated by Django 4.0.3 on 2022-06-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0125_alter_aboutuspagecms_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorganizationprofile',
            name='approved_once',
            field=models.BooleanField(default=False, verbose_name='Approved Once'),
        ),
    ]
