# Generated by Django 4.0.3 on 2022-06-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0126_alter_supplierorganizationprofile_approved_once'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course_category',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course Categories'),
        ),
    ]
