# Generated by Django 4.0.3 on 2022-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0127_alter_userprofile_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorganizationprofile',
            name='course_category',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course Category'),
        ),
        migrations.AlterField(
            model_name='supplierorganizationprofile',
            name='sub_category',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sub Category'),
        ),
    ]
