# Generated by Django 4.0.3 on 2022-06-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0128_alter_supplierorganizationprofile_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadpaymentdetail',
            name='is_approved',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status', verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='userpaymentdetail',
            name='is_approved',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status', verbose_name='Approval Status'),
        ),
    ]
