# Generated by Django 4.0.3 on 2022-06-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0129_eventadpaymentdetail_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadpaymentdetail',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Payment Mode'),
        ),
        migrations.AddField(
            model_name='userpaymentdetail',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Payment Mode'),
        ),
    ]
