# Generated by Django 4.0.3 on 2022-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0130_eventadpaymentdetail_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadpaymentdetail',
            name='admin_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Admin Name'),
        ),
        migrations.AddField(
            model_name='eventadpaymentdetail',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name'),
        ),
        migrations.AddField(
            model_name='userpaymentdetail',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier name'),
        ),
        migrations.AddField(
            model_name='userpaymentdetail',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User name'),
        ),
    ]
