# Generated by Django 4.0.3 on 2022-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0131_eventadpaymentdetail_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='course_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Price'),
        ),
    ]
