# Generated by Django 4.0.3 on 2022-06-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0132_alter_coursedetails_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventad',
            name='admin_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Admin Name'),
        ),
    ]
