# Generated by Django 4.0.3 on 2022-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0133_eventad_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventad',
            name='event_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Price'),
        ),
    ]
