# Generated by Django 4.0.3 on 2022-06-02 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0134_alter_eventad_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadpaymentdetail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='userpaymentdetail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
