# Generated by Django 4.0.3 on 2022-06-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0135_eventadpaymentdetail_uuid_userpaymentdetail_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Admin Email')),
                ('admin_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Admin Name')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('about_me', models.CharField(blank=True, max_length=1000, null=True, verbose_name='About Me')),
                ('admin_image', models.ImageField(blank=True, null=True, upload_to='admin_image/', verbose_name='Admin Image')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
            ],
            options={
                'verbose_name_plural': 'Admin Profile',
            },
        ),
    ]
