# Generated by Django 4.0.3 on 2022-06-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0136_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentdetail',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='userpaymentdetail',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Supplier Email ID'),
        ),
    ]
