# Generated by Django 4.0.3 on 2022-06-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0137_remove_userpaymentdetail_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganizationprofile',
            name='usersignup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup', verbose_name='User Signup'),
        ),
    ]
