# Generated by Django 4.0.3 on 2022-06-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0138_supplierorganizationprofile_usersignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.AddField(
            model_name='userpaymentdetail',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier name'),
        ),
    ]
