# Generated by Django 4.0.3 on 2022-06-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0139_delete_adminprofile_userpaymentdetail_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentdetail',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursedetails'),
        ),
    ]
