# Generated by Django 4.0.3 on 2022-06-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0140_userpaymentdetail_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentdetail',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='userpaymentdetail',
            name='supplier_email',
        ),
        migrations.RemoveField(
            model_name='userpaymentdetail',
            name='supplier_name',
        ),
    ]
