# Generated by Django 4.0.3 on 2022-06-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0141_remove_userpaymentdetail_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='course_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursesubcategorydetails', verbose_name='Course SubCategory'),
        ),
    ]
