# Generated by Django 4.0.3 on 2022-06-16 06:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0142_alter_coursedetails_course_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecmsbanner',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='homepagecmsbanner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='homepagecmsbanner',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagecmsbanner_sv',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='homepagecmsbanner_sv',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='homepagecmsbanner_sv',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepagecms',
            name='section_1_image',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.homepagecmsbanner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='homepagecms_sv',
            name='section_1_image',
            field=models.ManyToManyField(blank=True, null=True, to='eddi_app.homepagecmsbanner_sv', verbose_name='Banner'),
        ),
    ]
