# Generated by Django 4.0.3 on 2022-06-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0143_homepagecmsbanner_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecms',
            name='section_1_button_link',
        ),
        migrations.RemoveField(
            model_name='homepagecms',
            name='section_1_button_text',
        ),
        migrations.RemoveField(
            model_name='homepagecms',
            name='section_1_description',
        ),
        migrations.RemoveField(
            model_name='homepagecms',
            name='section_1_heading',
        ),
        migrations.RemoveField(
            model_name='homepagecms_sv',
            name='section_1_button_link',
        ),
        migrations.RemoveField(
            model_name='homepagecms_sv',
            name='section_1_button_text',
        ),
        migrations.RemoveField(
            model_name='homepagecms_sv',
            name='section_1_description',
        ),
        migrations.RemoveField(
            model_name='homepagecms_sv',
            name='section_1_heading',
        ),
    ]
