# Generated by Django 4.0.3 on 2022-06-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0144_remove_homepagecms_section_1_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='original_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Original Price'),
        ),
        migrations.AddField(
            model_name='eventad',
            name='original_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Original Price'),
        ),
    ]
