# Generated by Django 4.0.3 on 2022-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0145_coursedetails_original_price_eventad_original_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaybyInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Name')),
                ('personal_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Personal Number')),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Name')),
                ('organization_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Number')),
                ('street_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Number')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip')),
                ('contry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contry')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('invoice_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Invoice Address')),
                ('email_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email_id')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('event_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Event Name')),
                ('payment_mode', models.CharField(blank=True, max_length=500, null=True, verbose_name='Payment Mode')),
            ],
        ),
    ]
