# Generated by Django 4.0.3 on 2022-06-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0148_materialdocumentmaterial_document_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdocumentmaterial',
            name='document_title',
        ),
        migrations.RemoveField(
            model_name='materialvideomaterial',
            name='video_title',
        ),
        migrations.AddField(
            model_name='materialdocumentmaterial',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='File Name'),
        ),
        migrations.AddField(
            model_name='materialvideomaterial',
            name='video_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Video Name'),
        ),
        migrations.AlterField(
            model_name='coursesubcategorydetails',
            name='is_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.approval_status', verbose_name='Is_approved'),
        ),
        migrations.AlterField(
            model_name='coursesubcategorydetails',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type_id': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is_active'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Is_authenticated'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is_deleted'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_first_time_login',
            field=models.BooleanField(default=True, verbose_name='Is First Time Login'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='is_resetpassword',
            field=models.BooleanField(default=True, verbose_name='Is_resetpassword'),
        ),
    ]
