# Generated by Django 4.0.3 on 2022-06-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0149_remove_materialdocumentmaterial_document_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventad',
            name='admin_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Admin Email'),
        ),
    ]
