# Generated by Django 4.0.3 on 2022-06-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0150_eventad_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='original_price',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='offer_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Offer Price'),
        ),
        migrations.AlterField(
            model_name='materialdocumentmaterial',
            name='document_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='course_material_doc/', verbose_name='Document Files'),
        ),
        migrations.AlterField(
            model_name='materialvideomaterial',
            name='video_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='course_material_video/', verbose_name='Video Files'),
        ),
    ]
