# Generated by Django 4.0.3 on 2022-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0151_remove_coursedetails_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventad',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event End Date'),
        ),
    ]
