# Generated by Django 4.0.3 on 2022-07-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0152_eventad_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Device Token')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='created_date_time')),
                ('user_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup', verbose_name='User Type')),
            ],
            options={
                'verbose_name_plural': 'Notification Device Token',
            },
        ),
    ]
