# Generated by Django 4.0.3 on 2022-07-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0152_eventad_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='is_post',
            field=models.BooleanField(default=False, verbose_name='Is_post'),
        ),
    ]
