# Generated by Django 4.0.3 on 2022-07-21 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0155_alter_usersignup_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usertype', verbose_name='User Type'),
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID')),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Name')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Created By')),
                ('modified_by', models.CharField(blank=True, max_length=100, verbose_name='Modified By')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursedetails', verbose_name='Course')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.utl_status', verbose_name='Status')),
                ('students', models.ManyToManyField(blank=True, null=True, to='eddi_app.userprofile', verbose_name='Students')),
            ],
            options={
                'verbose_name_plural': 'Course Batch Table',
            },
        ),
    ]
