# Generated by Django 4.0.3 on 2022-07-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0156_alter_usersignup_user_type_coursebatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursebatch',
            old_name='created_datetime',
            new_name='created_date_time',
        ),
        migrations.RenameField(
            model_name='coursebatch',
            old_name='modified_datetime',
            new_name='modified_date_time',
        ),
    ]
