# Generated by Django 4.0.3 on 2022-07-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0157_rename_created_datetime_coursebatch_created_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='author_bio',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Author Bio'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='author_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Author Name'),
        ),
        migrations.CreateModel(
            name='BatchSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Name')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.DateTimeField(verbose_name='Session Start Time')),
                ('end_time', models.DateTimeField(verbose_name='Session End Time')),
                ('total_duration', models.CharField(max_length=100, verbose_name='Total Duration')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Url')),
                ('choose_days', models.CharField(max_length=100, null=True, verbose_name='Choose Day')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Created By')),
                ('modified_by', models.CharField(blank=True, max_length=100, verbose_name='Modified By')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.coursebatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name_plural': 'Batch Session Table',
            },
        ),
    ]
