# Generated by Django 4.0.3 on 2022-07-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0153_coursedetails_is_post'),
        ('eddi_app', '0158_coursedetails_author_bio_coursedetails_author_name_and_more'),
    ]

    operations = [
    ]
