# Generated by Django 4.0.3 on 2022-07-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0159_merge_20220722_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchsession',
            old_name='created_datetime',
            new_name='created_date_time',
        ),
        migrations.RenameField(
            model_name='batchsession',
            old_name='modified_datetime',
            new_name='modified_date_time',
        ),
        migrations.AddField(
            model_name='batchsession',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='batchsession',
            name='end_time',
            field=models.TimeField(verbose_name='Session End Time'),
        ),
        migrations.AlterField(
            model_name='batchsession',
            name='start_time',
            field=models.TimeField(verbose_name='Session Start Time'),
        ),
    ]
