# Generated by Django 4.0.3 on 2022-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0161_batchsession_custom_batchsession_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsession',
            name='customDays',
            field=models.CharField(max_length=100, null=True, verbose_name='Custom Days'),
        ),
    ]
