# Generated by Django 4.0.3 on 2022-07-27 06:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0162_batchsession_customdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID')),
                ('account_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Id')),
                ('total_earnings', models.FloatField(blank=True, null=True, verbose_name='Total Earnings')),
                ('total_amount_due', models.FloatField(blank=True, null=True, verbose_name='Total Amount Due')),
                ('total_amount_withdraw', models.FloatField(blank=True, null=True, verbose_name='Total Amount Withdraw')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_date_time', models.DateTimeField(auto_now=True, verbose_name='Modified Date Time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eddi_app.usersignup', verbose_name='Supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplier Account Details Table',
            },
        ),
    ]
