# Generated by Django 4.0.3 on 2022-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0163_supplieraccountdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybyinvoice',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student DOB'),
        ),
        migrations.AddField(
            model_name='paybyinvoice',
            name='invoice_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Method'),
        ),
        migrations.AddField(
            model_name='paybyinvoice',
            name='organization_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Reference'),
        ),
    ]
