# Generated by Django 4.0.3 on 2022-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0164_paybyinvoice_dob_paybyinvoice_invoice_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='author_bio',
            field=models.TextField(blank=True, null=True, verbose_name='Author bio'),
        ),
    ]
