# Generated by Django 4.0.3 on 2022-08-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0169_remove_paybyinvoice_email_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierpayoutdetail',
            options={'verbose_name_plural': 'Supplier Payout Details Table'},
        ),
    ]
