# Generated by Django 4.0.3 on 2022-08-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0170_alter_supplierpayoutdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieraccountdetail',
            name='commission',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission'),
        ),
    ]
