# Generated by Django 4.0.3 on 2022-09-12 11:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0173_supplierwithdrawaldetail_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='EddiLabsCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('banner', models.ImageField(upload_to='eddilabs_banner/', verbose_name='Banner Image')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
            ],
            options={
                'verbose_name_plural': 'Eddi Labs Table',
            },
        ),
        migrations.CreateModel(
            name='EddiLabsCMS_SV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('banner', models.ImageField(upload_to='eddilabs_banner/', verbose_name='Banner Image')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modified By')),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Date Time')),
            ],
            options={
                'verbose_name_plural': 'Eddi Labs Table SV',
            },
        ),
    ]
