# Generated by Django 4.0.3 on 2022-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddi_app', '0175_eddilabscms_button_link_eddilabscms_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='is_swedishdefault',
            field=models.BooleanField(default=True, verbose_name='Is_swedishdefault'),
        ),
    ]
